package com.lynx.core.classes;

import org.bukkit.*; import org.bukkit.entity.*; import org.bukkit.event.*; import org.bukkit.event.block.BlockBreakEvent; import org.bukkit.event.entity.EntityDamageByEntityEvent; import org.bukkit.event.player.PlayerInteractEvent; import org.bukkit.inventory.ItemStack; import org.bukkit.plugin.Plugin; import org.bukkit.potion.*; import org.bukkit.scheduler.BukkitRunnable;
import java.util.*; import java.util.concurrent.ConcurrentHashMap;

public final class PvPClassListener implements Listener {
    private final Plugin plugin; private final ClassManager manager; private final Map<UUID, Long> archerTags = new ConcurrentHashMap<UUID, Long>(); private final Map<UUID, Long> rogueCd = new ConcurrentHashMap<UUID, Long>();
    public PvPClassListener(Plugin plugin, ClassManager manager) { this.plugin = plugin; this.manager = manager; startEnergyTask(); }
    private void startEnergyTask() { new BukkitRunnable(){ public void run(){ for(Player p:Bukkit.getOnlinePlayers()){ PvPClass c=manager.refresh(p); if(c==PvPClass.BARD){ manager.addBardEnergy(p.getUniqueId(),1); bardHold(p); } passive(p,c); } }}.runTaskTimer(plugin,20L,20L); }
    private void passive(Player p, PvPClass c){ if(c==PvPClass.ARCHER){ effect(p,PotionEffectType.SPEED,60,2); effect(p,PotionEffectType.DAMAGE_RESISTANCE,60,1);} if(c==PvPClass.MINER){ effect(p,PotionEffectType.FAST_DIGGING,80,1); effect(p,PotionEffectType.NIGHT_VISION,220,0); if(p.getLocation().getBlockY()<30) effect(p,PotionEffectType.INVISIBILITY,80,0);} }
    private void bardHold(Player bard){ ItemStack hand=bard.getItemInHand(); if(hand==null) return; PotionEffectType type = hand.getType()==Material.SUGAR?PotionEffectType.SPEED:hand.getType()==Material.IRON_INGOT?PotionEffectType.DAMAGE_RESISTANCE:null; if(type==null) return; for(Player p:Bukkit.getOnlinePlayers()) if(p.getWorld().equals(bard.getWorld())&&p.getLocation().distanceSquared(bard.getLocation())<=400) effect(p,type,60,1); }
    @EventHandler(ignoreCancelled=true) public void onInteract(PlayerInteractEvent e){ if(manager.get(e.getPlayer())!=PvPClass.BARD||e.getItem()==null) return; int cost=0, amp=0; PotionEffectType type=null; Material m=e.getItem().getType(); if(m==Material.SUGAR){cost=20;type=PotionEffectType.SPEED;amp=2;} else if(m==Material.IRON_INGOT){cost=40;type=PotionEffectType.DAMAGE_RESISTANCE;amp=2;} else if(m==Material.BLAZE_POWDER){cost=50;type=PotionEffectType.INCREASE_DAMAGE;amp=1;} else if(m==Material.GHAST_TEAR){cost=40;type=PotionEffectType.REGENERATION;amp=2;} else if(m==Material.WHEAT){cost=15;type=PotionEffectType.SATURATION;amp=0;} if(type==null) return; if(!manager.spendBardEnergy(e.getPlayer().getUniqueId(),cost)){ e.getPlayer().sendMessage("§cNot enough bard energy."); return;} for(Player p:Bukkit.getOnlinePlayers()) if(p.getWorld().equals(e.getPlayer().getWorld())&&p.getLocation().distanceSquared(e.getPlayer().getLocation())<=400) effect(p,type,120,amp); }
    @EventHandler(ignoreCancelled=true) public void onDamage(EntityDamageByEntityEvent e){ Player damager = e.getDamager() instanceof Arrow && ((Arrow)e.getDamager()).getShooter() instanceof Player ? (Player)((Arrow)e.getDamager()).getShooter() : e.getDamager() instanceof Player ? (Player)e.getDamager() : null; if(!(e.getEntity() instanceof Player)||damager==null) return; Player victim=(Player)e.getEntity(); if(e.getDamager() instanceof Arrow && manager.get(damager)==PvPClass.ARCHER){ archerTags.put(victim.getUniqueId(),System.currentTimeMillis()+10000L); damager.sendMessage("§e"+victim.getName()+" §cis at §e"+Math.ceil(victim.getHealth()/2.0D)+"❤§c."); } if(archerTags.get(victim.getUniqueId())!=null&&archerTags.get(victim.getUniqueId())>System.currentTimeMillis()) e.setDamage(e.getDamage()*1.25D); if(manager.get(damager)==PvPClass.ROGUE && damager.getItemInHand()!=null && damager.getItemInHand().getType()==Material.GOLD_SWORD && behind(damager,victim) && ready(damager)){ e.setDamage(Math.max(e.getDamage(), victim.getHealth()-2.0D)); damager.getItemInHand().setDurability((short)Material.GOLD_SWORD.getMaxDurability()); rogueCd.put(damager.getUniqueId(),System.currentTimeMillis()+120000L); } }
    @EventHandler(ignoreCancelled=true) public void onMine(BlockBreakEvent e){ if(manager.get(e.getPlayer())==PvPClass.MINER && e.getBlock().getType()==Material.DIAMOND_ORE) e.getPlayer().sendMessage("§bFaction alert: diamond mined at " + loc(e.getBlock().getLocation())); }
    private boolean ready(Player p){ Long l=rogueCd.get(p.getUniqueId()); return l==null||l<System.currentTimeMillis(); } private boolean behind(Player a, Player v){ float diff=Math.abs(normalize(a.getLocation().getYaw()-v.getLocation().getYaw())); return diff<70.0F; } private float normalize(float f){ f%=360F; if(f< -180F)f+=360F; if(f>180F)f-=360F; return f; } private void effect(Player p,PotionEffectType t,int ticks,int amp){ p.addPotionEffect(new PotionEffect(t,ticks,amp),true); } private String loc(Location l){ return l.getBlockX()+","+l.getBlockY()+","+l.getBlockZ(); }
}
